version: '3.7'

networks:
  overlay-net:
    external: true

services:

  prod:
    image: iudx/cat-prod:latest
    environment:
      - HOSTNAME=server
      - ZOOKEEPER=zookeeper
      - CAT_URL=https://catalogue.iudx.org.in
      - LOG_LEVEL=INFO
    volumes:
      - ./configs/config-depl.json:/usr/share/app/configs/config.json
      - ./docs/:/usr/share/app/docs
      - ./configs/keystore.jks:/usr/share/app/configs/keystore.jks
      - ./ui/dist/:/usr/share/app/ui/dist
    depends_on:
      - "zookeeper"
    ports:
      - "8443:8443"
      - "9000:9000"
    restart: on-failure
    networks: 
      - overlay-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: "java -jar ./fatjar.jar -c configs/config.json"

  dev:
    image: dockerhub.iudx.io/jenkins/catalogue-dev
    environment:
      - CAT_URL=https://catalogue.iudx.org.in
      - LOG_LEVEL=DEBUG
    volumes:
      - ./configs/config-dev.json:/usr/share/app/configs/config.json
      - ./configs/keystore.jks:/usr/share/app/configs/keystore.jks
      - ./ui/dist/:/usr/share/app/ui/dist
    ports:
      - "8080:8080"
      - "9000:9000"
    restart: on-failure
    networks: 
      - overlay-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: "java -jar ./fatjar.jar -c configs/config.json"

  test:
    image: dockerhub.iudx.io/jenkins/catalogue-test
    environment:
      - CAT_URL=https://catalogue.iudx.org.in
      - WORKSPACE
      - LOG_LEVEL=DEBUG
    volumes:
      - /root/configs/cat-config-test.json:/usr/share/app/configs/config-test.json
      - ./src/:/usr/share/app/src
      - /root/configs/keystore.jks:/usr/share/app/configs/keystore.jks
      - ./docker/runTests.sh:/usr/share/app/docker/runTests.sh
      - ${WORKSPACE}:/tmp/test
    command: bash -c "docker/runTests.sh && cp -r target /tmp/test"
    networks: 
      - overlay-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
        
  perfTest:
    image: dockerhub.iudx.io/jenkins/catalogue-dev
    environment:
      - CAT_URL=https://catalogue.iudx.org.in
      - WORKSPACE
      - LOG_LEVEL=DEBUG
    volumes:
      - /root/configs/cat-config-test.json:/usr/share/app/configs/config-test.json
      - ./src/:/usr/share/app/src
      - /root/configs/keystore.jks:/usr/share/app/configs/keystore.jks
      - ./docker/runTests.sh:/usr/share/app/docker/runTests.sh
      - ${WORKSPACE}:/tmp/test
    #command: bash -c "mvn clean compile exec:java@catalogue-server"
    networks: 
      - overlay-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"

  zookeeper:
    image: zookeeper:latest
    expose: 
      - "2181"
    networks:
      - overlay-net
