version: '3.7'

networks:
  cat-net:
    driver: bridge

services:

  prod:
    image: iudx/cat-prod:latest
    environment:
      - HOSTNAME=server
      - ZOOKEEPER=zookeeper
      - CAT_URL=https://catalogue.iudx.org.in
    volumes:
      - ./configs/config-depl.json:/usr/share/app/configs/config.json
      - ./docs/:/usr/share/app/docs
      - ./configs/keystore.jks:/usr/share/app/configs/keystore.jks
      - ./ui/dist/:/usr/share/app/ui/dist
      - /tmp/iudx/:/tmp/iudx/
    depends_on:
      - "zookeeper"
    ports:
      - "8443:8443"
      - "9000:9000"
    restart: on-failure
    networks: 
      - cat-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: "java -jar ./fatjar.jar -c configs/config.json"

  dev:
    image: iudx/cat-dev:latest
    environment:
      - CAT_URL=https://catalogue.iudx.org.in
    volumes:
      - ./configs/config-dev.json:/usr/share/app/configs/config.json
      - ./configs/keystore.jks:/usr/share/app/configs/keystore.jks
      - ./ui/dist/:/usr/share/app/ui/dist
      - /tmp/iudx/:/tmp/iudx/
    ports:
      - "8080:8080"
      - "9000:9000"
    restart: on-failure
    networks: 
      - cat-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: "java -jar ./fatjar.jar -c configs/config.json"

  
  test:
    image: iudx/cat-test:latest
    environment:
      - CAT_URL=https://catalogue.iudx.org.in
    volumes:
      - ./src/:/usr/share/app/src
      - ./configs/config-test.json:/usr/share/app/configs/config-test.json
      - /tmp/test:/tmp/test
    command: bash -c "mvn clean test -Dtest=IntegrationTest && cp -r target /tmp/test"


    networks: 
      - cat-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"



  zookeeper:
    image: zookeeper:latest
    expose: 
      - "2181"
    networks:
      - cat-net
