version: '3.7'

networks:
  cat-net:
    driver: bridge

services:

  cat:
    image: iudx/cat-prod:latest
    environment:
      - CAT_URL=https://catalogue.iudx.org.in
      - LOG_LEVEL=INFO
      - CAT_JAVA_OPTS=-Xmx4096m
    volumes:
      - ./configs/config-depl.json:/usr/share/app/configs/config.json
      - ./configs/keystore.jks:/usr/share/app/configs/keystore.jks
    depends_on:
      - "zookeeper"
    ports:
      - "8080:8080"
      - "9000:9000"
    restart: on-failure
    networks: 
      - cat-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: bash -c "exec java $$CAT_JAVA_OPTS  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -jar ./fatjar.jar  --host $$(hostname) -c configs/config.json"

  dev:
    image: iudx/cat-dev:latest
    environment:
      - CAT_URL=https://catalogue.iudx.org.in
      - LOG_LEVEL=INFO
      - CAT_JAVA_OPTS=-Xmx1024m
    volumes:
      - ./configs/config-dev.json:/usr/share/app/configs/config.json
      - ./configs/keystore.jks:/usr/share/app/configs/keystore.jks
    ports:
      - "8080:8080"
      - "9000:9000"
    restart: on-failure
    networks: 
      - cat-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command:  bash -c "exec java $$CAT_JAVA_OPTS  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -jar ./fatjar.jar  --host $$(hostname) -c configs/config.json"

# Jenkins CI pipeline Unit test and Jacoco service
  test:
    image: ghcr.io/datakaveri/cat-test:latest
    environment:
      - CAT_URL=https://catalogue.iudx.org.in
      - WORKSPACE
      - LOG_LEVEL=INFO
    volumes:
      - /home/ubuntu/configs/cat-config-test.json:/usr/share/app/configs/config-test.json
      - ./src/:/usr/share/app/src
      - ./docker/runTests.sh:/usr/share/app/docker/runTests.sh
      - ${WORKSPACE}:/tmp/test
      - /var/run/docker.sock:/var/run/docker.sock
      - ./iudx-pmd-ruleset.xml:/usr/share/app/iudx-pmd-ruleset.xml
      - ./google_checks.xml:/usr/share/app/google_checks.xml
    command: bash -c "docker/runTests.sh && cp -r target /tmp/test"
    networks: 
      - cat-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
        
# Jenkins CI pipeline performance test service
  perfTest:
    image: ghcr.io/datakaveri/cat-prod:latest
    environment:
      - CAT_URL=https://catalogue.iudx.org.in
      - WORKSPACE
      - LOG_LEVEL=INFO
    volumes:
      - /home/ubuntu/configs/cat-config-dev.json:/usr/share/app/configs/config.json
    ports:
      - "8080:8080"
    command: bash -c "exec java $$CAT_JAVA_OPTS  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -jar ./fatjar.jar  --host $$(hostname) -c configs/config.json"
    networks: 
      - cat-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    depends_on:
      - "zookeeper"

  zookeeper:
    image: zookeeper:latest
    expose: 
      - "2181"
    networks:
      - cat-net
